### ISSUE TITLE
issue installing Graylog on SLES 12 sp3

### ISSUE THREAD

**Issue by wyasd-acshearer** [Graylog2/documentation#427] opened 2018-03-09 20:42 UTC
## Context
In the SLES install directions on the Graylog website I am trying to install the Graylog GPG key by following the directions here:

**First install the Graylog GPG Key with "rpm --import https://packages.graylog2.org/repo/debian/keyring.gpg" command**

I receive the Error message ---- Error: https://packages.graylog2.org/repo/debian/keyring.gpg: key 1 not an armored public key.

Is there a way to get this fixed?  I did go to install Graylog but get a message that 'repomd.xml' from repository 'graylog' is unsigned.  I wasn't sure if I received this because the Key did not import. I did not want to go through with install because without it being signed it can't be verified that no one messed with the file.  

If things don't work the best with SLES I can use another Linux distro, I was just using SLES since that is what all of our other servers are.  

## Your Environment

* Graylog Version: 2.4 when installed
* Elasticsearch Version: 5.6.8-1
* MongoDB Version: 3.6.3-1
* Operating System: SLES 12 SP3
* Browser version:

**Comment by joschi** [comment] 2018-03-10 09:00
Duplicate of Graylog2/fpm-recipes#81

> Is there a way to get this fixed?

You could probably download the keyring file and import it into your local keyring manually with `gpg`.

> I did go to install Graylog but get a message that 'repomd.xml' from repository 'graylog' is unsigned.

That's correct. We're currently not signing the repository metadata. You can set `repo_gpgcheck=0` (or a similar setting) in the repository definition on your system, see http://docs.graylog.org/en/2.4/pages/installation/operating_system_packages.html#id2

**Closed as completed by joschi** 2018-03-10 09:00 UTC

**Comment by wyasd-acshearer** [comment] 2018-03-12 14:19
Thank you for the information.  I appreciate it.

Andrew
