### ISSUE TITLE
Add a section about Securing Graylog

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/documentation#87] opened 2016-06-08 18:54 UTC
It might be good to refactor the documentation a bit, and to divide information a bit like
- Installing: "What takes to get it running"
- Configuring: "How to configure Graylog to accomplish stuff"
- Securing: "How to harden the setup"

Anyways, _Securing Graylog_ should collect together for example
- Enabling audit logging of usage (I will make a pull request of this very shortly)
- Network traffic profile (internal in cluster, outside, firewall requirements, etc)
- Configuring for cryptographic compliance (this part exists, it's brand new)
- Configuring "real" certificates for REST API and inputs
- How to add a legal disclaimer to login page, and to footer (I am using Apache's mod_substitute, but it's a hack)
- How to configure authentication (the pluggable authentication is in development, I'm especially interested in kerberos/GSSAPI and TLS client certificate authentication)
- What security maintenance tasks should be performed in production environments
- Other pieces of security related configuration that are all around the current documentation set

**Comment by joschi** [comment] 2016-06-09 15:31
@mikkolehtisalo Thanks, that's a very good idea!

**Comment by jalogisch** [comment] 2016-06-13 16:54
@mikkolehtisalo first part should be covered with https://github.com/Graylog2/documentation/commit/7e997f496fd33085ee16d035d85d35fe7bbc32ac what is your opinion on this?

**Comment by mikkolehtisalo** [comment] 2016-06-13 18:18
@jalogisch  Some good things there! In any case, many companies and such raise the questions "is X secure", and "how to harden X to achieve compliance Y" as a separate step in the process of approving  systems for use. Being able to find and verify all necessary (sometimes even small) details is important. 

Also, my thinking is that the documentation is growing. It needs more structure, or it becomes messy. (Mostly separating basic installation from extra configuration, which can vary greatly, but this also goes for some security topics that are strictly not mandatory...)

**Comment by jalogisch** [comment] 2016-06-14 12:35
@mikkolehtisalo i see your points. i personal had started to restructure the documentation a little with this https://github.com/Graylog2/documentation/pull/96 

Divide between simple and complex setups is not that easy as we would need to rewrite most parts of the documentation and change the logical structure. But we could add some points to the documentation to have them available. 

My idea would be to add:
- how to setup and use mongo in HA (in short what needs to be done within mongo and what needs to be configured on graylog)
- how a possible HA setup can look and how this can be secured best by design 

But it looks like you @mikkolehtisalo had some insides, what would needed from someone that has not knowledge about the moving parts and how to setup. Can you please suggest in detail what would be needed to fulfill the needs of someone who is looking from a non technical point into the documentation to archive compliance.
If you give us some hints what is needed we can add this step by step to the configuration.

**Comment by aoyawale** [comment] 2016-10-28 03:17
just wanted to share this for apache and nginx TLS config using stronger ciphers https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by jalogisch** [comment] 2020-07-22 07:10
We could never cover a complete security guide as all setups are different and have different needs. In addition MongoDB and Elasticsearch are on a second page - where the later has some fundamental questions to answer before you can decide about the security (OSS Elasticsearch VS Enterprise Elasticsearch).

Will close this and we will/have already in mind to include more information how to secure something PLUS the product will improve in this section.

**Closed as completed by jalogisch** 2020-07-22 07:10 UTC
Labels: help wanted, needs-input, documentation, feature, triaged
